name: octo_pet_wear_os
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  wear: ^1.1.0
  animated_widgets: ^1.1.0
  audiofileplayer: ^2.1.0
  localstorage: ^4.0.0+1
  flutter_launcher_icons: ^0.9.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  icons_launcher: ^1.1.7

flutter_icons:
  image_path: 'assets/icon/ic_logo_border.png'
  ios: true
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/sfx/
    - assets/icon/
    - assets/images/
    - assets/images/emotes/
    - assets/images/pet/
    - assets/images/pet/ambient/
  fonts:
    - family: EarlyGameboy
      fonts:
        - asset: assets/fonts/Early-Gameboy.ttf